export const DATA_FETCH_TEMPERATURE = 'DATA_FETCH_TEMPERATURE'
export const DATA_FETCH_WATER = 'DATA_FETCH_WATER'
export const DATA_FETCH_LUX = 'DATA_FETCH_LUX'

export const MANAGE_DATA_DELETE_TEMPERATURE = 'MANAGE_DATA_DELETE_TEMPERATURE'
export const MANAGE_DATA_DELETE_WATER = 'MANAGE_DATA_DELETE_WATER'
export const MANAGE_DATA_DELETE_LUX = 'MANAGE_DATA_DELETE_LUX'